### ISSUE TITLE
WABLAS_TOKEN issue

### ISSUE THREAD

**Issue by hendivalon** [shadowbane/laravel-wablas#1]
![image](https://user-images.githubusercontent.com/54342125/124820837-2f81f080-df98-11eb-8d27-1a0f92f88919.png)

I did input the token thru .env file , although hard code in the config/laravel-wablas.php

**Comment by shadowbane** [comment]
Have you clear your config cache?
Can you send full error details, it will helps me debug the error.

edit: I see you're using `artisan serve`. try restarting the server

**Comment by shadowbane** [comment]
Is it solved? I will close this issue now. Feel free to reopen if you had any problem regarding WABLAS_TOKEN
