### ISSUE TITLE
Error when install on laravel 9

### ISSUE THREAD

**Issue by hendivalon** [shadowbane/laravel-wablas#2]
Halo Mas Adly,

I found issue when just fresh install the packages. 
i just run this command
`composer require shadowbane/laravel-wablas`

Then got this error on terminal

<img width="724" alt="Screen Shot 2022-09-04 at 23 02 06" src="https://user-images.githubusercontent.com/54342125/188322625-0f89fb50-7e49-4f0e-afbf-96c7e52c3c7c.png">

do you have an update on this library ?

**Comment by shadowbane** [comment]
Halo Mas Hendi. Sorry for really late reply. I've been busy with work lately.
Actually, I have abandoned this, as I quite disappointed by their service when they are moving to version 2. Check out [shadowbane/laravel-whatsmeow](https://github.com/shadowbane/laravel-whatsmeow) for my own spin, using gomeow as server
